### ISSUE TITLE
Restore Blockstack ID via Secret Recovery Key

### ISSUE THREAD

**Issue by alvesjtiago** [Casa/BlockstackBrowser-ios#27]
When trying to recover my blockstack ID through the Secret Recovery Key, I always get "Incorrect code or password". I'm pretty sure this is the correct one since on the laptop I’m able to export the backup keychain using this password.
Happy to provide any other info about this and help debug the issue.  Thank you!

![simulator screen shot - iphone 8 plus - 2018-06-02 at 10 37 09](https://user-images.githubusercontent.com/407470/40869640-527226b4-6651-11e8-91b5-3d511b78cfd5.png)

**Comment by larrysalibra** [comment]
Thanks for this @alvesjtiago - this package is deprecated and not used or supported - i think you're looking for: https://github.com/blockstack/blockstack-ios

**Comment by alvesjtiago** [comment]
Thanks @larrysalibra! Filing a new one on that repo 👍
